# -*- coding: utf-8 -*-
"""HOG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ca48VnSw9MTJ8b0tvSYDbrfKuLCvyitl
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt
from skimage.feature import hog
from skimage import exposure

# 1. Read the image
image_path = "/content/capybara.jpg"  # Colab uploads go to /content/
image = cv2.imread(image_path)

if image is None:
    raise ValueError("Image not found. Check the image path.")

# Convert BGR to RGB (for display)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Convert to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# 2. Apply HOG Feature Extraction
features, hog_image = hog(
    gray,
    orientations=9,
    pixels_per_cell=(8, 8),
    cells_per_block=(2, 2),
    block_norm='L2-Hys',
    visualize=True
)

# Rescale HOG image for better visualization
hog_image_rescaled = exposure.rescale_intensity(
    hog_image, in_range=(0, 10)
)

# 3. Display Results
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.title("Original Image")
plt.imshow(image_rgb)
plt.axis("off")

plt.subplot(1, 2, 2)
plt.title("HOG Feature Visualization")
plt.imshow(hog_image_rescaled, cmap='gray')
plt.axis("off")

plt.tight_layout()
plt.show()

# 4. Print Feature Vector Size
print("HOG feature vector length:", len(features))

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt
from skimage.feature import hog
from skimage import exposure

# 1. Read the image
image_path = "/content/shin.jpg"  # Colab uploads go to /content/
image = cv2.imread(image_path)

if image is None:
    raise ValueError("Image not found. Check the image path.")

# Convert BGR to RGB (for display)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Convert to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# 2. Apply HOG Feature Extraction
features, hog_image = hog(
    gray,
    orientations=9,
    pixels_per_cell=(8, 8),
    cells_per_block=(2, 2),
    block_norm='L2-Hys',
    visualize=True
)

# Rescale HOG image for better visualization
hog_image_rescaled = exposure.rescale_intensity(
    hog_image, in_range=(0, 10)
)

# 3. Display Results
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.title("Original Image")
plt.imshow(image_rgb)
plt.axis("off")

plt.subplot(1, 2, 2)
plt.title("HOG Feature Visualization")
plt.imshow(hog_image_rescaled, cmap='gray')
plt.axis("off")

plt.tight_layout()
plt.show()

# 4. Print Feature Vector Size
print("HOG feature vector length:", len(features))